# Generated by Django 4.2.19 on 2025-03-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
